### ISSUE TITLE
请问文件传输我点击文件后没反应，需要开python服务器么？

### ISSUE THREAD

**Issue by csuyanchong** [CrankZ/ScreenSharing-FileTransfer-in-LAN#3]
另外就是想请问master端显示的传输进度是怎么获取的？

**Comment by CrankZ** [comment]
文件传输原理就是Python搭建一个HTTP服务器，然后局域网下载。
master获得传输进度，很简单粗暴，就是slave把通过TCP/UDP把自己下载进度传到master
